changelog:
  categories:
    - title: Dependency updates
      labels:
        - dependencies
    - title: Security
      labels:
        - security
    - title: Features, fixes, and documentation
      labels:
        - '*'
